force-app/main/default/objects/Event_Notification_Archive__c/Event_Notification_Archive__c.object-meta.xml
<CustomObject>
    <label>Event Notification Archive</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event Notification Archive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Notification Archives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Notification_Archive__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Notification_Archive__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Notification_Archive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Request_Details__c.field-meta.xml
<CustomField>
    <fullName>Request_Details__c</fullName>
    <label>Request Details</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SR_Notification__e/SR_Notification__e.object-meta.xml
<CustomObject>
    <label>SR Notification</label>
    <pluralLabel>SR Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/SR_Notification__e/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SR_Notification__e/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SR_Notification__e/fields/Service_Request_Details__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Details__c</fullName>
    <label>Service Request Details</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SR_Notification__e/fields/Service_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Id__c</fullName>
    <label>Service Request Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SR_Notification__e/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SR_Notification__e/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceRequestTriggerHandler.cls
public with sharing class ServiceRequestTriggerHandler {

    public static void notifyOnNewServiceRequest(List<Service_Request__c> serviceRequests) {
        List<SR_Notification__e> srNotificationList = new List<SR_Notification__e>();
        /* NOTE: This list is used in the big object example */
        //List<SR_Notification_Archive__b> notificationArchive = new List<SR_Notification_Archive__b>();

        /* NOTE: This list is used in the custom object archive example */
        List<Event_Notification_Archive__c> eventNotificationList = new List<Event_Notification_Archive__c>();

        for (Service_Request__c sr : serviceRequests)
        {
            boolean processSR = false;
            system.debug('$$ Order ' + sr.Name + ': ' + sr.Id + ' is ' + sr.Status__c);
            //Only process submitted orders
            if (sr.Status__c == 'New')
            {
                SR_Notification__e srNotification = new SR_Notification__e();
                srNotification.Customer_Name__c = sr.Name;
                srNotification.Service_Request_Details__c = sr.Request_Details__c;
                srNotification.Service_Request_Id__c = sr.Id;
                srNotification.Street__c = sr.Street__c;
                srNotification.City__c = sr.City__c;
                srNotification.State__c = sr.State__c;
                srNotification.Country__c = sr.Country__c;
                srNotification.Postal_Code__c = sr.Postal_Code__c;
                system.debug('srNotification json $$ ' + JSON.serialize(srNotification));
                srNotificationList.add(srNotification); 

                /* NOTE: This section is an example on how to archive to the associated big object.
                 * There are pros and cons to using custom objects to archive
                 */ 
                Event_Notification_Archive__c newArchive = new Event_Notification_Archive__c();
                newArchive.Event__c = 'SR_Notification__e';
                newArchive.Status__c = 'New';
                newArchive.Payload__c = JSON.serialize(srNotification);
                eventNotificationList.add(newArchive);

                /* NOTE: This section is an example on how to archive to the associated big object.
                 * There are pros and cons to using Big Objects 
                 */ 
                /*
                SR_Notification_Archive__b newArchive = new SR_Notification_Archive__b();
                newArchive.event__c = 'SR_Notification__e';
                newArchive.Status__c = 'New';
                newArchive.Payload__c = JSON.serialize(srNotification);
                notificationArchive.add(newArchive);
                */

                
                

                
            }
            
        }
        
        

        if (!srNotificationList.isEmpty())
        {
            List<Database.SaveResult> saveResults = EventBus.publish(srNotificationList);
            for (Integer i = 0; i < saveResults.size(); i++) {
                Database.SaveResult r =  saveResults[i];
                if (r.isSuccess())
                {
                    system.debug('Save Result $$ ' + r.getId() + ' is success ');
                    String result = EventBus.getOperationId(r);
                    system.debug('Async result uuid ' + result);

                    /* making the assumption that the event order is same as notification order */
                    /*NOTE: This is used for the archive to big object */
                    //notificationArchive[i].UUID__c = result;

                    /*NOTE: This is used for the archive to custom object */
                    eventNotificationList[i].UUID__c = result;

                    
                }
                else {
                    for (Database.Error err : r.getErrors())
                    {
                        System.debug('Save result ' + r.getId() + ' ' + err.getStatusCode() + ': ' + err.getMessage());

                    }
                    
                }
                
            }
            /* Archive Process for custom object
             * NOTE: This section is an example on how to archive to the associated custom object.
             * There are pros and cons to using custom objects to archive
             */ 
            insert eventNotificationList;


            /* Archive Process for Big Objects
             * NOTE: This section is an example on how to archive to the associated big object.
             * There are pros and cons to using custom objects to archive
             */ 
            /*SRNotificationArchival handler = new SRNotificationArchival(notificationArchive);
            System.enqueueJob(handler);*/



        }

    }
}